#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef LUCKIEVERSE_SWIFT_H
#define LUCKIEVERSE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Luckieverse",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Luckieverse",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class UIViewController;
SWIFT_CLASS("_TtC11Luckieverse21FloatingButtonManager")
@interface FloatingButtonManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FloatingButtonManager * _Nonnull shared;)
+ (FloatingButtonManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)showFloatingButtonOn:(UIViewController * _Nonnull)viewController;
- (void)hideFloatingButton;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
SWIFT_CLASS("_TtC11Luckieverse18LuckieverseAdError")
@interface LuckieverseAdError : NSObject
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
- (nonnull instancetype)initWithCode:(NSInteger)code message:(NSString * _Nullable)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11Luckieverse17LuckieverseAdInfo")
@interface LuckieverseAdInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull zoneId;
@property (nonatomic, readonly, copy) NSString * _Nullable network;
@property (nonatomic, readonly, copy) NSString * _Nullable adType;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId network:(NSString * _Nullable)network adType:(NSString * _Nullable)adType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LuckieverseCalendarType, "LuckieverseCalendarType", open) {
  LuckieverseCalendarTypeINIT = -1,
  LuckieverseCalendarTypeSOLAR = 0,
  LuckieverseCalendarTypeLUNAR = 1,
  LuckieverseCalendarTypeLUNAR_LEAP = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, LuckieverseChineseZodiacTime, "LuckieverseChineseZodiacTime", open) {
  LuckieverseChineseZodiacTimeINIT = -1,
  LuckieverseChineseZodiacTimeJA = 0,
  LuckieverseChineseZodiacTimeCHUK = 1,
  LuckieverseChineseZodiacTimeIN = 2,
  LuckieverseChineseZodiacTimeMYO = 3,
  LuckieverseChineseZodiacTimeJIN = 4,
  LuckieverseChineseZodiacTimeSA = 5,
  LuckieverseChineseZodiacTimeO = 6,
  LuckieverseChineseZodiacTimeMI = 7,
  LuckieverseChineseZodiacTimeSHIN = 8,
  LuckieverseChineseZodiacTimeYU = 9,
  LuckieverseChineseZodiacTimeSUL = 10,
  LuckieverseChineseZodiacTimeHAE = 11,
  LuckieverseChineseZodiacTimeUNKNOWN = 12,
};

typedef SWIFT_ENUM_NAMED(NSInteger, LuckieverseGender, "LuckieverseGender", open) {
  LuckieverseGenderINIT = -1,
  LuckieverseGenderMALE = 0,
  LuckieverseGenderFEMALE = 1,
};

SWIFT_ENUM_FWD_DECL(NSInteger, LuckieverseLocalPushType)
@class UNNotificationSound;
SWIFT_CLASS("_TtC11Luckieverse20LuckieverseLocalPush")
@interface LuckieverseLocalPush : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title body:(NSString * _Nonnull)body type:(enum LuckieverseLocalPushType)type repeats:(BOOL)repeats sound:(UNNotificationSound * _Nonnull)sound interverInSeconds:(NSInteger)interverInSeconds OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LuckieverseLocalPushType, "LuckieverseLocalPushType", open) {
  LuckieverseLocalPushTypeMAIN = 876663,
  LuckieverseLocalPushTypeMY = 876664,
  LuckieverseLocalPushTypeSAJU_INFO = 876665,
  LuckieverseLocalPushTypePHONE_AUTH = 876666,
  LuckieverseLocalPushTypePOINT_HISTORY = 876667,
  LuckieverseLocalPushTypePRODUCT_HISTORY = 876668,
  LuckieverseLocalPushTypePRODUCT_HISTORY_DETAIL = 876669,
  LuckieverseLocalPushTypeFAQ = 876670,
  LuckieverseLocalPushTypeFAQ_DETAIL = 876671,
  LuckieverseLocalPushTypeINQUIRY = 876672,
  LuckieverseLocalPushTypeINQUIRY_HISTORY = 876673,
  LuckieverseLocalPushTypeINQUIRY_HISTORY_DETAIL = 876674,
  LuckieverseLocalPushTypeTERMS_AND_POLICIES = 876675,
  LuckieverseLocalPushTypeTERMS_AND_POLICIES_DETAIL = 876676,
  LuckieverseLocalPushTypePRODUCT_STORE = 876677,
  LuckieverseLocalPushTypePRODUCT_STORE_DETAIL = 876678,
  LuckieverseLocalPushTypeERROR = 876679,
};

SWIFT_ENUM_FWD_DECL(NSInteger, LuckieverseZodiac)
SWIFT_CLASS("_TtC11Luckieverse14LuckieverseSDK")
@interface LuckieverseSDK : NSObject
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull noADErrorCodeList;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LuckieverseSDK * _Nonnull shared;)
+ (LuckieverseSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)setFloatingButtonWithViewController:(UIViewController * _Nonnull)viewController show:(BOOL)show;
- (void)setConsumableFullscreenZoneIds:(NSArray<NSString *> * _Nonnull)zoneIds;
- (void)setConsumableBannerZoneIds:(NSArray<NSString *> * _Nonnull)zoneIds;
/// 풀스크린 광고 load() 진입 후 응답이 없을 때 타임아웃 처리까지 대기하는 시간(초)을 설정한다. 기본 40초.
/// 1.0초 미만(음수/0/NaN/Infinity 포함)은 무시되고 기존 값이 유지된다.
/// 주의: 40초 미만으로 설정하면 showRVWithDynamicZoneID의 내부 no-fill 타이머(40초 고정)보다 먼저 발화하여,
/// 해당 경로의 콜백이 onAdNoFill() 대신 onLoadFail(타임아웃 에러)로 전달될 수 있다.
- (void)setFullscreenAdLoadTimeout:(NSTimeInterval)timeout;
/// 풀스크린 광고 show() 진입 후 onClose 없이 응답이 없을 때 타임아웃 처리까지 대기하는 시간(초)을 설정한다. 기본 180초.
/// 1.0초 미만(음수/0/NaN/Infinity 포함)은 무시되고 기존 값이 유지된다.
- (void)setFullscreenAdShowTimeout:(NSTimeInterval)timeout;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)setSdkVersion:(NSString * _Nonnull)value;
@property (nonatomic, readonly, copy) NSString * _Nonnull birth;
@property (nonatomic, readonly) enum LuckieverseCalendarType calendarType;
@property (nonatomic, readonly) enum LuckieverseChineseZodiacTime chineseZodiacTime;
@property (nonatomic, readonly) enum LuckieverseGender gender;
@property (nonatomic, readonly) enum LuckieverseZodiac zodiac;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)initialize;
- (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
- (void)setSDKVersionWithVersion:(NSString * _Nonnull)version;
- (void)updateUSER_IDWithUserId:(NSString * _Nonnull)userId;
- (void)updateIDFAWithIDFA:(NSString * _Nonnull)IDFA;
- (void)updateAPP_KEYWithAPP_KEY:(NSString * _Nonnull)APP_KEY;
- (void)updateMAIN_KEYWithMAIN_KEY:(NSString * _Nonnull)MAIN_KEY;
- (void)update_TAROT_APP_KEYWithAPP_KEY:(NSString * _Nonnull)APP_KEY;
- (void)update_GAME_APP_KEYWithAPP_KEY:(NSString * _Nonnull)APP_KEY;
- (void)enableBannerDebug:(BOOL)debug;
- (void)enableFullScreenAdFailForTest:(BOOL)enable;
- (void)updateBannerHeightLimit:(CGFloat)height;
- (void)updateWebviewInspector:(BOOL)enabled;
- (void)setGoToSettingObjc:(void (^ _Nonnull)(void))callback;
- (void)setGoToSettingSwift:(void (^ _Nonnull)(void))callback;
- (void)openLuckieverseTarot;
- (void)openLuckieverseGame;
- (void)openLuckieverseMain;
- (void)openLuckieverseByPushWithPushKey:(NSString * _Nonnull)pushKey;
- (void)openLuckieverseTarotByPushWithPushKey:(NSString * _Nonnull)pushKey;
- (void)openLuckieverseGameByPushWithPushKey:(NSString * _Nonnull)pushKey;
- (void)openLuckieverseMyPage;
- (void)openLuckieverseSajuInfo;
- (void)openLuckieversePhoneAuth;
- (void)openLuckieversePointHistory;
- (void)openLuckieverseProductHistory;
- (void)openLuckieverseProductHistoryDetailWithId:(NSString * _Nonnull)id;
- (void)openLuckieverseFaq;
- (void)openLuckieverseFaqDetailWithId:(NSString * _Nonnull)id;
- (void)openLuckieverseInquiry;
- (void)openLuckieverseInquiryHistory;
- (void)openLuckieverseInquiryHistoryDetailWithId:(NSString * _Nonnull)id;
- (void)openLuckieverseTermsAndPolicies;
- (void)openLuckieverseTermsAndPoliciesDetailWithId:(NSString * _Nonnull)id;
- (void)openLuckieverseProductStore;
- (void)openLuckieverseProductStoreDetail;
- (void)openLuckieverseError;
- (void)setLuckieverseLocalPushWithPush:(LuckieverseLocalPush * _Nonnull)push;
- (void)cancelLuckieverseLocalPushWithPushType:(enum LuckieverseLocalPushType)pushType;
/// 이메일 앱을 엽니다
- (void)openEmailAppWithRecipient:(NSString * _Nullable)recipient;
- (void)openNewYearFortune;
- (void)openFaceReading;
- (void)showRVWithDynamicZoneID:(NSString * _Nonnull)zoneID;
- (void)showRVWithDynamicZoneID:(NSString * _Nonnull)zoneID onLoadFail:(void (^ _Nullable)(LuckieverseAdError * _Nonnull))onLoadFail onAdComplete:(void (^ _Nullable)(LuckieverseAdInfo * _Nonnull))onAdComplete onAdNoFill:(void (^ _Nullable)(void))onAdNoFill onAdBlockUser:(void (^ _Nullable)(void))onAdBlockUser;
- (void)showRVWithDynamicZoneID:(NSString * _Nonnull)zoneID onLoadFail:(void (^ _Nullable)(LuckieverseAdError * _Nonnull))onLoadFail onAdComplete:(void (^ _Nullable)(LuckieverseAdInfo * _Nonnull))onAdComplete onAdNoFill:(void (^ _Nullable)(void))onAdNoFill onAdBlockUser:(void (^ _Nullable)(void))onAdBlockUser onAdLoad:(void (^ _Nullable)(void))onAdLoad onAdShow:(void (^ _Nullable)(LuckieverseAdInfo * _Nonnull))onAdShow onAdSkip:(void (^ _Nullable)(void))onAdSkip onAdClose:(void (^ _Nullable)(LuckieverseAdInfo * _Nonnull))onAdClose onAdClick:(void (^ _Nullable)(LuckieverseAdInfo * _Nonnull))onAdClick;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LuckieverseZodiac, "LuckieverseZodiac", open) {
  LuckieverseZodiacINIT = -1,
  LuckieverseZodiacAQUARIUS = 0,
  LuckieverseZodiacPISCES = 1,
  LuckieverseZodiacARIES = 2,
  LuckieverseZodiacTAURUS = 3,
  LuckieverseZodiacGEMINI = 4,
  LuckieverseZodiacCANCER = 5,
  LuckieverseZodiacLEO = 6,
  LuckieverseZodiacVIRGO = 7,
  LuckieverseZodiacLIBRA = 8,
  LuckieverseZodiacSCORPIO = 9,
  LuckieverseZodiacSAGITTARIUS = 10,
  LuckieverseZodiacCAPRICORN = 11,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
